artifacts_root: artifacts

data_ingestion:
    root_dir: artifacts/data_ingestion
    service: s3
    region: us-east-1
    bucket_name: reynaml
    aws_file: LI-Small_Trans.csv
    download_path: artifacts/data_ingestion/data.csv
    aws_access_key_id: AKIA3FLD6AHRLWGNRLTF
    aws_secret_access_key: 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


